market:
  open-on-start: true
  day-minutes: 30
  tick-seconds: 60
  transaction-fee-percent: 1.0
  max-price-change-percent-per-tick: 12.0
  min-trade-value: 1.0
  max-trade-value: 100000.0
  price-history-limit-per-asset: 500

limit-orders:
  enabled: true
  execute-offline-players: false
  max-open-per-player: 10

leaderboards:
  size: 10
  min-daily-gain-value: 1.0

gui:
  title: "MC Stocks"
  stock-quick-amounts:
    - 1
    - 10
    - 64
  crypto-quick-amounts:
    - 0.1
    - 1
    - 10
